### ISSUE TITLE
The remote server returned an error: (404) Not Found. After version 3599

### ISSUE THREAD

**Issue by terrabys** [sinscove/Yuzu-Updater#16]
Updater version Yuzu.Updater.1.5.2

Last successful update was version 3599
Since then I get this in the log:
18:13 - ERROR - The remote server returned an error: (404) Not Found.
18:13 - ERROR -    at System.Net.HttpWebRequest.GetResponse()
   at Yuzu_Updater.DownloadManager.<>c__DisplayClass2_0.<Download>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Yuzu_Updater.DownloadManager.<Download>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Yuzu_Updater.MainForm.<DownloadVersion>d__12.MoveNext()

**Comment by terrabys** [comment]
[Solved] Working after deleting all the updater files, and extracting them from the zip again, instead of overriding the existing once.

**Comment by terrabys** [comment]
The issue persists if I delete the updater the initial download works, but every subsequent downloads fails, same thing if I change the version and press install.
log:
18:43 - INFO - Fetching list of older versions
18:43 - INFO - Fetched list of older versions!
18:43 - INFO - Retrieved Database Info
18:43 - INFO - Downloading Update: 3609
18:43 - INFO - Extracting files..
This may take a while..
18:43 - INFO - Cleaning Up
18:43 - INFO - Done!
18:45 - INFO - Downloading version 3608
This may take a while..
18:45 - INFO - An error occurred, please check the logs for the issue
18:45 - ERROR - The remote server returned an error: (404) Not Found.
18:45 - ERROR -    at System.Net.HttpWebRequest.GetResponse()
   at Yuzu_Updater.DownloadManager.<>c__DisplayClass2_0.<Download>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Yuzu_Updater.DownloadManager.<Download>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Yuzu_Updater.MainForm.<DownloadVersion>d__12.MoveNext()

**Comment by Sin213** [comment]
Fixed on new version.
